### ISSUE TITLE
Tests break with Clojure 1.9 stable release

### ISSUE THREAD

**Issue by tirkarthi** [plandes/clj-actioncli#3]
The tests work with Clojure 1.9-RC-2 but they break with the stable release. Seems there is a difference which is strange. Attaching the result of the failing test cases as below : 

Clojure 1.9.0-RC-2

```
➜  clj-actioncli git:(master) ✗ lein with-profile +1.9 repl
nREPL server started on port 39932 on host 127.0.0.1 - nrepl://127.0.0.1:39932
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.9.0-RC2
OpenJDK 64-Bit Server VM 9-internal+0-2016-04-14-195246.buildd.src

user=> (require '[zensols.actioncli.resource :refer :all])
nil
user=> (register-resource :root-pkg :constant "clojure" :type :resource)
#object[zensols.actioncli.resource$eval1786$fn__1787 0x1a13c0a6 "zensols.actioncli.resource$eval1786$fn__1787@1a13c0a6"]
user=> (.toString (resource-path :root-pkg))
"jar:file:/root/.m2/repository/org/clojure/clojure/1.9.0-RC2/clojure-1.9.0-RC2.jar!/clojure"
user=> (re-matches #"^jar:file:.*org/clojure/clojure/[0-9A-Z-.]+/clojure-[0-9A-Z-.]+.jar!/clojure" (.toString (resource-path :root-pkg)))
"jar:file:/root/.m2/repository/org/clojure/clojure/1.9.0-RC2/clojure-1.9.0-RC2.jar!/clojure"
```

Clojure 1.9.0

```
➜  clj-actioncli git:(master) ✗ lein with-profile +1.9 repl
nREPL server started on port 40601 on host 127.0.0.1 - nrepl://127.0.0.1:40601
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.9.0
OpenJDK 64-Bit Server VM 9-internal+0-2016-04-14-195246.buildd.src

user=> (require '[zensols.actioncli.resource :refer :all])
nil
user=> (register-resource :root-pkg :constant "clojure" :type :resource)
#object[zensols.actioncli.resource$eval1786$fn__1787 0x193590c "zensols.actioncli.resource$eval1786$fn__1787@193590c"]
user=> (.toString (resource-path :root-pkg))
"jar:file:/root/.m2/repository/org/clojure/tools.reader/1.1.1/tools.reader-1.1.1.jar!/clojure"
```

The above should be returning "jar:file:/root/.m2/repository/org/clojure/clojure/1.9.0/clojure-1.9.0.jar!/clojure" which causes the regex to fail.

**Comment by plandes** [comment]
The tests were breaking because it found resource packages in the `tools.reader` package before the main `Clojure` jar due to a class path ordering issue.  All the test needs to do is to make sure resource resolution works so I changed the test to use a different dependency (`pool`).  I've now put out [release 0.0.27](https://github.com/plandes/clj-actioncli/releases/tag/v0.0.27), which is also now available on *clojars* as before.

Note that I haven't yet put out a new release of [clj-nlp-parse](https://github.com/plandes/clj-nlp-parse) yet since explicitly giving the `clj-actioncli` dependency will override the `clj-nlp-parse` library implicitly or explicitly with `:exclusions`.
